### ISSUE TITLE
Trace.CorrelationManager.LogicalOperationStack is incompatible with async/await

### ISSUE THREAD

**Issue by ohadschn** [sgryphon/essential-diagnostics#24]
Basically it uses a mutable stack in the logical call context, [which behaves badly with async/await](https://stackoverflow.com/questions/28769483/is-logicaloperationstack-incompatible-with-async-in-net-4-5/30130663#30130663). Since [LogicalOperationScope](https://github.com/sgryphon/essential-diagnostics/blob/19f9259f0729cd42eaf8c51d2d48756c02bfa499/src/Essential.Diagnostics.Fluent/Diagnostics/LogicalOperationScope.cs) is using `LogicalOperationStack`, it too is broken for `async`/`await`.

The simplest way to fix this would be to use an [immutable stack instead](https://stackoverflow.com/a/24468972/67824).

**Comment by sgryphon** [comment]
The Trace.CorrelationManager class is from the .NET Framework, not Essential Diagnostics. You need to report this issue to Microsoft, as there is nothing that the extensions can do about it.

Thanks for the note, however. Perhaps I could add a warning to the relevant classes/documentation.

**Comment by ohadschn** [comment]
The extension can simply not use it, opting for a custom made immutable stack...

**Comment by sgryphon** [comment]
"The extension can simply not use it"

Not sure how you would expect that to work.

At the moment, if you set Trace.CorrelationManager.StartLogicalOperation() directly, and then configure to write the output to, say, FileLogTraceListener with traceOutputOptions="LogicalOperationStack", then the values you set will be included in the output.

The LogicalOperationScope class just gives a wrapper around starting and stopping LogicalOperationStack, that automatically disposes, etc. The output works the same.

But, what would be the point, unless I am missing something, of setting a custom immutable stack value? How would it get into the output of FileLogTraceListener?

**Comment by ohadschn** [comment]
Good point. I forgot the `LogicalOperationStack` is tied to the actual tracing like that. Perhaps you could write your own listeners that use your custom immutable logical stack?

**Comment by sgryphon** [comment]
I happened to look at this again, and found a fix; at least for Essential.Diagnostics. 

The CorrrelationManager mostly works correctly, but you need to force / trigger the clone in the nested contexts (so that push/pop works correctly). 

If you are accessing via the Essential Diagnostics scope wrapper, new LogicalOperationScope(), then I have added a line that touches the execution context before calling StartLogicalOperation(), which triggers the clone and fixes the problem.

There is a unit test added to demonstrate the issue; it is in a separate commit, so if you get that commit the test will fail; the following commit then fixes the stack to work.

Note that this won't help if you are manually calling StartLogicalOperation() -- although you would just need to add the line yourself to touch the context -- but will fix the issue when the Essential Diagnostics scope helper is used.
